name = "frontend"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
rsvp = ">= 1.1.3 and < 2.0.0"
middle = { path = "../middle/" }
plinth = ">= 0.8.0 and < 1.0.0"
modem = ">= 2.1.2 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.2.3 and < 3.0.0"

[tools.lustre.build]
minify = true
# Build the application into our server's `priv/static` directory so it can be
# deployed together with the backend.
# outdir = "../server/priv/static"

[tools.lustre.dev]
host = "localhost"
port = 1234
proxy = { from = "/api", to = "http://localhost:8080/api" }
